baseUrl = https://automationexercise.com
browser = chrome
headless = false
acceptInsecureCerts = false

# Page load strategy: normal = full load, eager = DOM ready, none = no page-load wait
pageLoadStrategy = eager

reportPath = ./reports/Report_
reportTitle = Automation Exercise - Test Execution Report